const oldBeers = [
    {
        "id": 79,
        "name": "APEROL SPRITZ DE BARRIL",
        "brand": "La Birra es Bella",
        "price": 400,
        "on_tap": 1,
        "category": "COCTEL",
        "subcategory": "",
        "ibu": "-",
        "abv": "∼ 11",
        "description": "Spritz clásico (partes iguales de espumante y Aperol + un dash de soda) alimentado en barril con pieles de cítricos que elevan su carácter.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2FLaBirra-logo.png?alt=media&token=bda9b872-0eee-4b42-97a5-8ae32861626d"
    },
    {
        "id": 78,
        "name": "GIN TONIC DE BARRIL",
        "brand": "La Birra es Bella",
        "price": 400,
        "on_tap": 1,
        "category": "COCTEL",
        "subcategory": "",
        "ibu": "-",
        "abv": " ∼ 7",
        "description": "Gin tonic con un proceso de maceración en cedrón, pieles de limas, pimienta de jamaica y bayas de enebro, que lo hacen evolucionar conforme pasa el tiempo.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2FLaBirra-logo.png?alt=media&token=bda9b872-0eee-4b42-97a5-8ae32861626d"
    },
    {
        "id": 81,
        "name": "NEGRONI DE BARRIL",
        "brand": "La Birra es Bella",
        "price": 400,
        "on_tap": 1,
        "category": "COCTEL",
        "subcategory": "",
        "ibu": "-",
        "abv": "∼ 28,5",
        "description": "Sin ser irreverentes, se mantiene la receta clásica, de partes iguales de gin, Campari y vermú rosso. La magia ocurre luego en la maceración, que da por resultado un Negroni distinto, con notas de canela, clavo de olor y pomelo rosado.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2FLaBirra-logo.png?alt=media&token=bda9b872-0eee-4b42-97a5-8ae32861626d"
    },
    {
        "id": 147,
        "name": "VERMOUTH CASERO",
        "brand": "LA BIRRA ES BELLA",
        "price": 200,
        "on_tap": 1,
        "category": "COCTEL",
        "subcategory": "",
        "ibu": "-",
        "abv": 6,
        "description": "El auténtico 70/30, más un plus de la receta secreta de Paladar Negro Original, puro sabor para disfrutar acompañado de empanaditas de carne o red beef, y gran aliado de nuestro famoso pincho de bife de chorizo. De baja graduación alcohólica, está macerado en hierbas y pieles de naranjas y pomelos.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2FLaBirra-logo.png?alt=media&token=bda9b872-0eee-4b42-97a5-8ae32861626d"
    },
    {
        "id": 205,
        "name": "VINO TIRADO BLANCO",
        "brand": "PALA CORAZÓN",
        "price": 250,
        "on_tap": 1,
        "category": "COCTEL",
        "subcategory": "",
        "ibu": "",
        "abv": "",
        "description": "Variedad de uvas blancas tantas secas como dulces, siendo un blend de tintas con notas florales, con marcada acidez que le brinda mucha frescura.",
        "imagen": ""
    },
    {
        "id": 82,
        "name": "AMERICAN WHEAT",
        "brand": "CONNER",
        "price": 300,
        "on_tap": 1,
        "category": "GOLDEN",
        "subcategory": "AMERICAN WHEAT",
        "ibu": 20,
        "abv": 3.8,
        "description": "Cerveza dorada, pálida con pequeña nubosidad. Buena retención de espuma de color blanco y pequeñas burbujas. El aroma remite al pan blanco y a un leve pero distinguible lúpulo cítrico.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fconner-logo.jpg?alt=media&token=a89c168c-3215-41c6-bfe7-cfc54acf0fa3"
    },
    {
        "id": 49,
        "name": "KOLSCH",
        "brand": "FAUCARIA",
        "price": 300,
        "on_tap": 1,
        "category": "GOLDEN",
        "subcategory": "",
        "ibu": 20,
        "abv": 4.7,
        "description": "Cerveza limpia, fresca y balanceada, sutil aroma a fruta y lúpulo. Amargor medio-bajo.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Ffaucaria-logo.png?alt=media&token=8129479d-3a96-42f0-b611-8db950eaf4e9"
    },
    {
        "id": 113,
        "name": "CANILLA EN MANTENIMIENTO",
        "brand": "Estamos trabajando para traerte lo mejor 🤗",
        "price": 300,
        "on_tap": 5,
        "category": "",
        "subcategory": "",
        "ibu": "-",
        "abv": "-",
        "description": "La sacamos a boxes un ratito para seguir trayéndote las mejores birras. ¡Volvé más tarde y descubrí qué pinchamos!",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/nada-logo.png?alt=media&token=83fff0f6-8a93-4c4a-9e86-dcd0afc4582c"
    },
    {
        "id": 35,
        "name": "HOPPY BLONDE",
        "brand": "KALBER MATTER",
        "price": 300,
        "on_tap": 1,
        "category": "GOLDEN",
        "subcategory": "",
        "ibu": 25,
        "abv": 4.7,
        "description": "Las sutil presencia de lúpulo refleja tonos frutales, cítricos y florales, tanto en su sabor como en el aroma.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fkalbermatter-logo.jpg?alt=media&token=c581682e-6540-4bb5-8ea0-5836f77246bd"
    },
    {
        "id": 113,
        "name": "CANILLA EN MANTENIMIENTO",
        "brand": "Estamos trabajando para traerte lo mejor 🤗",
        "price": 300,
        "on_tap": 5,
        "category": "",
        "subcategory": "",
        "ibu": "-",
        "abv": "-",
        "description": "La sacamos a boxes un ratito para seguir trayéndote las mejores birras. ¡Volvé más tarde y descubrí qué pinchamos!",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/nada-logo.png?alt=media&token=83fff0f6-8a93-4c4a-9e86-dcd0afc4582c"
    },
    {
        "id": 113,
        "name": "CANILLA EN MANTENIMIENTO",
        "brand": "Estamos trabajando para traerte lo mejor 🤗",
        "price": 300,
        "on_tap": 5,
        "category": "",
        "subcategory": "",
        "ibu": "-",
        "abv": "-",
        "description": "La sacamos a boxes un ratito para seguir trayéndote las mejores birras. ¡Volvé más tarde y descubrí qué pinchamos!",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/nada-logo.png?alt=media&token=83fff0f6-8a93-4c4a-9e86-dcd0afc4582c"
    },
    {
        "id": 113,
        "name": "CANILLA EN MANTENIMIENTO",
        "brand": "Estamos trabajando para traerte lo mejor 🤗",
        "price": 300,
        "on_tap": 5,
        "category": "",
        "subcategory": "",
        "ibu": "-",
        "abv": "-",
        "description": "La sacamos a boxes un ratito para seguir trayéndote las mejores birras. ¡Volvé más tarde y descubrí qué pinchamos!",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/nada-logo.png?alt=media&token=83fff0f6-8a93-4c4a-9e86-dcd0afc4582c"
    },
    {
        "id": 17,
        "name": "APA CARANCHO",
        "brand": "OKCIDENTA",
        "price": 350,
        "on_tap": 1,
        "category": "APA",
        "subcategory": "",
        "ibu": 30,
        "abv": 6.7,
        "description": "Sociable, equilibrada y refrescante. De color dorado y estupendo aroma a lúpulos frescos, cítricos y notas a maracuyá. Muy balanceada para disfrutar en todo momento. Ideal para maridar con quesos jóvenes, picadas, sushi o comidas especiadas o picantes.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fokcidenta-logo.jpg?alt=media&token=8615e2dc-165c-46b2-8ff9-91994b28dc63"
    },
    {
        "id": 165,
        "name": "APA",
        "brand": "CONNER",
        "price": 300,
        "on_tap": 1,
        "category": "APA",
        "subcategory": "",
        "ibu": 28,
        "abv": 5.6,
        "description": "Es una cerveza con aromas herbaceos provenientes de lúpulos Mosaic y refrescante tomabilidad por su cuerpo ligero. Refrescante y con notas dulces, tiene un cuerpo balanceado y un final seco.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fconner-logo.jpg?alt=media&token=a89c168c-3215-41c6-bfe7-cfc54acf0fa3"
    },
    {
        "id": 139,
        "name": "APA",
        "brand": "NOMADA",
        "price": 300,
        "on_tap": 1,
        "category": "APA",
        "subcategory": "",
        "ibu": 30,
        "abv": 5.2,
        "description": "Ligera con una explosion de flores citricos y herbal",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fnomada-logo.png?alt=media&token=6e8cfa80-3d7f-41ee-b2b9-a69e0906fd4b"
    },
    {
        "id": 93,
        "name": "APA - AMERICAN PALE ALE",
        "brand": "NEMESIS",
        "price": 300,
        "on_tap": 1,
        "category": "APA",
        "subcategory": "",
        "ibu": 33,
        "abv": 4.7,
        "description": "Una birra sin comentarios",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fnemesis-logo.png?alt=media&token=9820027c-f469-4ee2-b1f1-0c61a3b79e76"
    },
    {
        "id": 85,
        "name": "AMERICAN IPA",
        "brand": 372,
        "price": 300,
        "on_tap": 1,
        "category": "IPA",
        "subcategory": "AMERICAN IPA",
        "ibu": 42,
        "abv": 6,
        "description": "Fuerte amargor, floral y cítrica.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2F372-logo.jpg?alt=media&token=b466a2fb-d701-4a8d-89fb-a24a86cd8256"
    },
    {
        "id": 151,
        "name": "IPA",
        "brand": "NOMADA",
        "price": 300,
        "on_tap": 1,
        "category": "IPA",
        "subcategory": "",
        "ibu": 50,
        "abv": 5.6,
        "description": "Aroma moderado a lúpulo mostrando fruta tropical, pomelo, melón.Aromas que pasan a boca acompañados de un equilibrio de hierba, minerales y dulce residual.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fnomada-logo.png?alt=media&token=6e8cfa80-3d7f-41ee-b2b9-a69e0906fd4b"
    },
    {
        "id": 175,
        "name": "CACHORRO",
        "brand": "LA BIRRA ES BELLA y FAUCARIA",
        "price": 300,
        "on_tap": 1,
        "category": "IPA",
        "subcategory": "",
        "ibu": 30,
        "abv": 5.5,
        "description": "¡Exclusiva de La Birra es Bella! ¡Pedila YA!",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2FLaBirraYFaucaria-cachorro.png?alt=media&token=92a9e3a3-1ce0-4721-a50a-16b7c18c7f19"
    },
    {
        "id": 113,
        "name": "CANILLA EN MANTENIMIENTO",
        "brand": "Estamos trabajando para traerte lo mejor 🤗",
        "price": 300,
        "on_tap": 5,
        "category": "",
        "subcategory": "",
        "ibu": "-",
        "abv": "-",
        "description": "La sacamos a boxes un ratito para seguir trayéndote las mejores birras. ¡Volvé más tarde y descubrí qué pinchamos!",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/nada-logo.png?alt=media&token=83fff0f6-8a93-4c4a-9e86-dcd0afc4582c"
    },
    {
        "id": 169,
        "name": "DOBLE IPA",
        "brand": "OKCIDENTA",
        "price": 370,
        "on_tap": 1,
        "category": "IPA",
        "subcategory": "",
        "ibu": 60,
        "abv": 9,
        "description": "Equilibrado en amargor y alcohol, aroma y sabor citrico, seca en paladar.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fokcidenta-logo.jpg?alt=media&token=8615e2dc-165c-46b2-8ff9-91994b28dc63"
    },
    {
        "id": 186,
        "name": "AMERICAN IPA",
        "brand": "NEMESIS",
        "price": 300,
        "on_tap": 1,
        "category": "IPA",
        "subcategory": "",
        "ibu": 60,
        "abv": 6,
        "description": "",
        "imagen": ""
    },
    {
        "id": 137,
        "name": "AMBER",
        "brand": "RUTHERFORD",
        "price": 300,
        "on_tap": 1,
        "category": "RED",
        "subcategory": "",
        "ibu": 26,
        "abv": 4.6,
        "description": "Cerveza amber ligera con sutiles notas de caramelo, aroma a lupulo intermedio",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/rutherford-logo.png?alt=media&token=bcaabfed-1817-4117-8042-162430f3ff31"
    },
    {
        "id": 37,
        "name": "IRISH RED ALE",
        "brand": "ANFORA",
        "price": 300,
        "on_tap": 1,
        "category": "RED",
        "subcategory": "",
        "ibu": 23,
        "abv": 5,
        "description": "Cerveza roja de color cobrizo, cuerpo intenso, y amargor leve, sabor suave con notas a caramelo y frutos secos.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fanfora-logo.png?alt=media&token=dc0420a6-1b0c-4f9e-aa95-04bb289265f2"
    },
    {
        "id": 101,
        "name": "IMPERIAL BROWN",
        "brand": "PSICOTELLA",
        "price": 300,
        "on_tap": 1,
        "category": "RED",
        "subcategory": "",
        "ibu": "N/A",
        "abv": "N/A",
        "description": "Aún no hay datos cargados para esta cerveza, preguntale a un mozo/a",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fpsicotella-logo.png?alt=media&token=47b249c3-fa2e-473b-9db8-d7e7aff4ad4c"
    },
    {
        "id": 21,
        "name": "AMERICAN AMBER ALE",
        "brand": "KALBER MATTER",
        "price": 300,
        "on_tap": 1,
        "category": "RED",
        "subcategory": "AMBER",
        "ibu": 35,
        "abv": 5.5,
        "description": "El dulzor de la malta se equilibra con un generoso lupulado en múltiples adiciones que, con sus aceites, imparten notas citricas y florales.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fkalbermatter-logo.jpg?alt=media&token=c581682e-6540-4bb5-8ea0-5836f77246bd"
    },
    {
        "id": 177,
        "name": "IRISH RED ALE",
        "brand": "CONNER",
        "price": 300,
        "on_tap": 1,
        "category": "RED",
        "subcategory": "",
        "ibu": 20,
        "abv": 5,
        "description": "",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fconner-logo.jpg?alt=media&token=a89c168c-3215-41c6-bfe7-cfc54acf0fa33"
    },
    {
        "id": 54,
        "name": "IRISH RED ALE",
        "brand": "PALO Y HUESO",
        "price": 300,
        "on_tap": 1,
        "category": "RED",
        "subcategory": "",
        "ibu": 30,
        "abv": 4.6,
        "description": "De color rojizo. Aroma y sabor delicado a caramelo, con leve tostado y frutal.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fpaloyhueso-logo.jpg?alt=media&token=7e9f968c-a26a-4f4f-a8d2-24c366abe582"
    },
    {
        "id": 102,
        "name": "SCOTCH",
        "brand": "FAUCARIA",
        "price": 300,
        "on_tap": 1,
        "category": "RED",
        "subcategory": "",
        "ibu": 19,
        "abv": 5.7,
        "description": "Centrada en las maltas caramelo, con leve aroma a esteres. Sus lúpulos balancean el dulzor de las mismas. Color cobre solido, espuma moderada, clara y cremosa. Sabores de malta con matices acaramelados y tostados. Cuerpo medio-bajo.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Ffaucaria-logo.png?alt=media&token=8129479d-3a96-42f0-b611-8db950eaf4e9"
    },
    {
        "id": 211,
        "name": "SCOTCH STRONG ALE",
        "brand": "NOMADA",
        "price": 300,
        "on_tap": 1,
        "category": "RED",
        "subcategory": "",
        "ibu": 26,
        "abv": 6.1,
        "description": "Plenamente maltoso, con caramelización. Notas de malta torrada o sabores ahumados pueden estar presentes, así como algo de carácter a nuez; todos ellos deben perdurar en el acabado. Los sabores a lúpulo y el amargor son de bajos a medio-bajos, de forma tal de que la malta predomine",
        "imagen": ""
    },
    {
        "id": 190,
        "name": "RED ALE",
        "brand": "BORNEO",
        "price": 300,
        "on_tap": 1,
        "category": "RED",
        "subcategory": "",
        "ibu": 18,
        "abv": 5,
        "description": "Su sabor y aroma nos recuerda a una irish, tostada levemente amarga, con notas a caramelo y frutos secos.",
        "imagen": "http://www.borneobrewingco.com.ar/img/brand.jpg"
    },
    {
        "id": 1,
        "name": "PORTER",
        "brand": "BAUM",
        "price": 300,
        "on_tap": 1,
        "category": "DARK",
        "subcategory": "",
        "ibu": 30,
        "abv": 5,
        "description": "Cerveza nacida en los antiguos puertos londinenses, oscura con leves reflejos rubí y en la que la malta tostada tiene un gran protagonismo produciendo aromas y sabores que nos recuerdan a chocolate, café torrado y toffe.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fbaum-logo.jpg?alt=media&token=31cecba8-43f6-48d0-8f58-be43f21d93af"
    },
    {
        "id": 4,
        "name": "GLADSTONE STOUT",
        "brand": "BAUM",
        "price": 300,
        "on_tap": 1,
        "category": "DARK",
        "subcategory": "",
        "ibu": 30,
        "abv": 5,
        "description": "De tonalidad oscura profunda, con sabores a café, torrado y chocolate aportado por las maltas especiales, en balance con las notas de a roble y whisky que nos recuerdan sutilmente al coco y vainilla.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Fbaum-logo.jpg?alt=media&token=31cecba8-43f6-48d0-8f58-be43f21d93af"
    },
    {
        "id": 129,
        "name": "MILK STOUT",
        "brand": "FAUCARIA",
        "price": 300,
        "on_tap": 1,
        "category": "DARK",
        "subcategory": "",
        "ibu": 22,
        "abv": 5,
        "description": "De cuerpo medio, sedoso por el agregado de lactosa, de aroma y sabor a maltas tostadas con notas a nueces y frutas secas.",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/menuvirtual-birras.appspot.com/o/logos-cervecerias%2Ffaucaria-logo.png?alt=media&token=8129479d-3a96-42f0-b611-8db950eaf4e9"
    }
]

export default oldBeers;